#%%
NAMES_HELPSEEKER = [
    "Jordan", "Sam", "Morgan", "Casey", "Riley", "Quinn", "Avery", "Taylor", "Jamie", "Drew",
    "Skyler", "Reese", "Finley", "Rowan", "Sage", "Parker", "Cameron", "Charlie", "Dakota",
    "Devon", "Emerson", "Harper", "Hayden", "Jesse", "Kai", "Kendall", "Lane", "Lee", "Marley",
    "Micah", "Noel", "Phoenix", "River", "Robin", "Shawn", "Sidney", "Terry", "Tristan", "Wren",
    "Mike", "Danny", "Chris", "Matt", "Jake", "Ryan", "Brian", "Kevin", "Tom", "Ben", "Nick",
    "Steve", "Eric", "Jason", "Mark", "David", "Adam", "Andrew", "Brad", "Brandon", "Caleb",
    "Cody", "Daniel", "Ethan", "Frank", "George", "Greg", "Henry", "Jack", "James", "Jeff", "John",
    "Josh", "Justin", "Kyle", "Luke", "Nathan", "Noah", "Paul", "Peter", "Robert", "Scott", "Sean",
    "Tim", "Tyler", "Will", "Zach", "Sarah", "Emily", "Jessica", "Rachel", "Lauren", "Amanda",
    "Megan", "Katie", "Lisa", "Jenny", "Nicole", "Ashley", "Heather", "Stephanie", "Becky", "Tina",
    "Abigail", "Allison", "Anna", "Brittany", "Chloe", "Courtney", "Danielle", "Elizabeth", "Emma",
    "Erin", "Gabrielle", "Grace", "Hannah", "Jillian", "Julia", "Kelly", "Kim", "Kristen", "Laura",
    "Madison", "Molly", "Natalie", "Olivia", "Samantha", "Vanessa", "Victoria", "Zoe", "Priya",
    "Raj", "Ananya", "Vikram", "Neha", "Arjun", "Kavita", "Sanjay", "Deepa", "Amit", "Sunita",
    "Rohan", "Meera", "Aditya", "Pooja", "Nikhil", "Asha", "Rahul", "Kiran", "Divya", "Isha",
    "Shreya", "Varun", "Siddharth", "Gaurav", "Pranav", "Shruti", "Sneha", "Manish", "Suresh",
    "Jaya", "Mahesh", "Payal", "Tanvi", "Anil", "Ritu", "Wei", "Ming", "Jing", "Chen", "Lin",
    "Hui", "Xin", "Lei", "Yan", "Feng", "Hong", "Ping", "Ling", "Jun", "Mei", "Tao", "Li", "Xiao",
    "Ying", "Lan", "Bo", "Rui", "Yao", "Qiang", "Shu", "Zhi", "Zhen", "Ting", "Guo", "Shan",
    "Yuki", "Kenji", "Sakura", "Haruto", "Aiko", "Takeshi", "Naomi", "Ryo", "Akira", "Hiroshi",
    "Hana", "Kaito", "Emi", "Satoshi", "Yoko", "Ren", "Mika", "Shin", "Aya", "Daichi", "Mai",
    "Ryota", "Carlos", "Maria", "Diego", "Sofia", "Miguel", "Isabella", "Javier", "Lucia", "Rosa",
    "Marco", "Elena", "Luis", "Carmen", "Pedro", "Ana", "Rafael", "Juan", "Jose", "Andres",
    "Fernando", "Gabriel", "Alejandro", "Francisco", "Ricardo", "Manuel", "Pablo", "Roberto",
    "Daniela", "Gabriela", "Valeria", "Camila", "Mariana", "Natalia", "Patricia", "Veronica",
    "Luisa", "Luca", "Giulia", "Francesca", "Alessandro", "Chiara", "Matteo", "Valentina",
    "Giovanni", "Paolo", "Stefano", "Federico", "Giorgio", "Filippo", "Alberto", "Claudia",
    "Silvia", "Martina", "Elisa", "Giovanna", "Davide", "Simone", "Fatima", "Omar", "Layla",
    "Hassan", "Zahra", "Karim", "Nadia", "Amir", "Ali", "Reza", "Yasmin", "Samira", "Farah",
    "Noor", "Amina", "Khalid", "Hadi", "Samir", "Salma", "Maryam", "Zain", "Rami", "Jin", "Soo",
    "Minji", "Hyun", "Jae", "Yuna", "Jisoo", "Jihoon", "Seojun", "Eunji", "Sumin", "Taehyun",
    "Hyejin", "Seungmin", "Joon", "Jiwoo", "Oleksandr", "Katya", "Dmitri", "Anya", "Ivan",
    "Natasha", "Andrei", "Nikolai", "Sergei", "Mikhail", "Viktor", "Olga", "Irina", "Anastasia",
    "Yulia", "Svetlana", "Pavel", "Boris", "Mila", "Kwame", "Amara", "Kofi", "Zara", "Malik",
    "Jabari", "Adewale", "Chidi", "Chioma", "Ngozi", "Nnamdi", "Lerato", "Thandi", "Zanele",
    "Remy", "Camille", "Julien", "Pierre", "Luc", "Hugo", "Celine", "Amelie", "Sophie", "Andre",
    "Marcel", "Nina", "Lars", "Sven", "Ingrid", "Greta", "Anja", "Heidi", "Klaus", "Hans", "Lea",
    "Nils", "Anh", "Thuy", "Trang", "Huy", "Tuan", "Phuong", "Lan", "Minh", "Bao", "Aria", "Narin",
    "Somchai", "Priyom", "Lani", "Mariel",
]
WORDS_COMMON = [
    "tomorrow", "yesterday", "weekend", "morning", "afternoon", "evening", "midnight", "deadline",
    "schedule", "calendar", "hourly", "weekly", "monthly", "later", "earlier", "coffee", "laptop",
    "phone", "notebook", "window", "desk", "chair", "keyboard", "screen", "folder", "charger",
    "headphones", "printer", "bottle", "blanket", "remember", "forget", "check", "update",
    "review", "confirm", "finish", "start", "pause", "continue", "adjust", "organize", "compare",
    "arrange", "submit", "quick", "simple", "perfect", "great", "excellent", "solid", "smooth",
    "clean", "fresh", "ready", "basic", "obvious", "tricky", "urgent", "flexible", "office",
    "home", "building", "floor", "room", "hallway", "parking", "elevator", "lobby", "kitchen",
    "garage", "bedroom", "bathroom", "garden", "basement", "manager", "colleague", "teammate",
    "intern", "boss", "client", "vendor", "partner", "assistant", "director", "neighbor", "cousin",
    "landlord", "stranger", "guest", "busy", "tired", "relieved", "frustrated", "excited",
    "confused", "confident", "nervous", "curious", "satisfied", "overwhelmed", "relaxed",
    "impatient", "grateful", "skeptical", "email", "message", "meeting", "lunch", "break",
    "project", "report", "document", "version", "draft", "budget", "recipe", "password",
    "reminder", "backup",
]
CONTEXT_CATEGORIES = {
    "education_homework": {
        "description": "Students seeking help with schoolwork",
        "subcategories": [
            "solving algebra equations",
            "understanding geometry proofs",
            "writing a history essay",
            "studying geography for a test",
            "reviewing biology concepts",
            "working through physics problems",
            "analyzing a piece of literature",
            "translating foreign language text",
            "preparing for a standardized test",
            "memorizing vocabulary for a quiz",
            "outlining a research paper",
            "preparing for a group presentation",
            "studying for final exams",
            "taking better notes in class",
            "managing homework after school",
        ],
    },
    "personal_finance": {
        "description": "Budgeting, savings, investments",
        "subcategories": [
            "creating a monthly budget",
            "building an emergency fund",
            "understanding IRA options",
            "managing a stock portfolio",
            "paying off credit card debt",
            "improving a credit score",
            "filing taxes as a freelancer",
            "saving for college tuition",
            "tracking daily expenses",
            "assessing investment risk",
            "setting up automatic savings",
            "cutting monthly subscriptions",
            "planning for a large purchase",
            "choosing a checking account",
            "splitting bills with a roommate",
        ],
    },
    "health_wellness": {
        "description": "Fitness, nutrition, general health",
        "subcategories": [
            "starting a running routine",
            "building a workout plan",
            "choosing healthy snacks",
            "managing stress levels",
            "improving sleep habits",
            "tracking calorie intake",
            "stretching before exercise",
            "staying hydrated",
            "dealing with back pain",
            "choosing vitamins and supplements",
            "sticking to a new habit",
            "recovering from a minor injury",
            "finding time to exercise",
            "handling allergy season",
            "getting more steps in each day",
        ],
    },
    "travel_planning": {
        "description": "Trip logistics, destinations, tips",
        "subcategories": [
            "booking affordable flights",
            "finding a good hotel",
            "planning a road trip route",
            "packing efficiently",
            "getting travel insurance",
            "navigating a new city",
            "managing a travel budget",
            "choosing a vacation destination",
            "handling jet lag",
            "traveling internationally for the first time",
            "planning a long weekend trip",
            "choosing between hotel and rental",
            "finding activities at a destination",
            "dealing with a canceled flight",
            "traveling with a large group",
        ],
    },
    "cooking_recipes": {
        "description": "Meal prep, techniques, recipes",
        "subcategories": [
            "learning to bake bread",
            "meal prepping for the week",
            "making pasta from scratch",
            "grilling steak properly",
            "cooking a vegetarian dinner",
            "using a slow cooker",
            "making sushi at home",
            "baking a birthday cake",
            "preparing a holiday meal",
            "trying a new cuisine",
            "planning weeknight dinners",
            "making a simple soup",
            "roasting vegetables",
            "cooking rice consistently",
            "putting together a cheese board",
        ],
    },
    "home_improvement": {
        "description": "Repairs, renovations, DIY projects",
        "subcategories": [
            "painting a room",
            "fixing a leaky faucet",
            "installing shelves",
            "replacing a light fixture",
            "organizing a closet",
            "building a garden bed",
            "weatherproofing windows",
            "refinishing a wood floor",
            "setting up a home office",
            "cleaning gutters",
            "rearranging a living room",
            "hanging pictures on the wall",
            "deep cleaning the kitchen",
            "decluttering a garage",
            "assembling flat-pack furniture",
        ],
    },
    "career_professional": {
        "description": "Job search, workplace, professional growth",
        "subcategories": [
            "writing a resume",
            "preparing for a job interview",
            "negotiating a salary",
            "managing a team project",
            "giving a presentation",
            "dealing with workplace conflict",
            "asking for a promotion",
            "networking at events",
            "switching careers",
            "managing work-life balance",
            "writing a cover letter",
            "preparing for a performance review",
            "giving feedback to a coworker",
            "organizing a busy workweek",
            "handling a difficult manager",
        ],
    },
    "shopping_consumer": {
        "description": "Product research, buying decisions",
        "subcategories": [
            "choosing a new laptop",
            "comparing phone plans",
            "finding deals on furniture",
            "buying a mattress",
            "picking running shoes",
            "shopping for groceries on a budget",
            "choosing kitchen appliances",
            "buying a gift for someone",
            "comparing streaming services",
            "selecting home cleaning products",
            "buying a winter coat",
            "choosing a new coffee maker",
            "picking out a backpack",
            "buying a set of headphones",
            "shopping for a birthday present",
        ],
    },
    "entertainment": {
        "description": "Movies, games, hobbies, music",
        "subcategories": [
            "finding a good book to read",
            "picking a movie for movie night",
            "learning to play guitar",
            "starting a new board game",
            "discovering new music",
            "getting into photography",
            "planning a game night",
            "watching a TV series",
            "learning to draw or sketch",
            "starting a podcast",
            "picking up a new hobby",
            "choosing a puzzle to work on",
            "trying a new card game",
            "making a weekend plan with friends",
            "starting a journal",
        ],
    },
    "writing_communication": {
        "description": "Emails, letters, creative writing",
        "subcategories": [
            "writing a professional email",
            "drafting a thank-you note",
            "composing a complaint letter",
            "writing a personal statement",
            "editing an essay",
            "preparing a speech",
            "writing a blog post",
            "crafting a social media bio",
            "responding to a formal invitation",
            "journaling daily",
            "writing a birthday card message",
            "drafting a short toast for a dinner",
            "writing an out-of-office reply",
            "drafting a message to reconnect with a friend",
            "writing a short review online",
        ],
    },
    "legal_questions": {
        "description": "Everyday legal matters and rights",
        "subcategories": [
            "understanding a lease agreement",
            "filing a small claims case",
            "dealing with a parking ticket",
            "understanding tenant rights",
            "setting up a basic will",
            "disputing a charge on a bill",
            "understanding warranty terms",
            "navigating insurance claims",
            "understanding employment contracts",
            "handling a neighbor dispute",
            "getting a security deposit back",
            "understanding a cell phone contract",
            "contesting a late fee",
            "understanding a gym membership agreement",
            "dealing with a canceled order",
        ],
    },
    "parenting_family": {
        "description": "Childcare, family dynamics, activities",
        "subcategories": [
            "helping a child with homework",
            "managing screen time for kids",
            "planning family activities",
            "handling sibling rivalry",
            "preparing for a new baby",
            "choosing a daycare",
            "teaching kids about money",
            "organizing a family vacation",
            "dealing with teenage behavior",
            "cooking meals kids will eat",
            "setting up a bedtime routine",
            "planning a kids birthday party",
            "helping a child make friends",
            "managing chores with kids",
            "handling visits with grandparents",
        ],
    },
    "pet_care": {
        "description": "Animal care, training, health",
        "subcategories": [
            "training a new puppy",
            "choosing the right dog food",
            "taking care of a cat",
            "setting up an aquarium",
            "dealing with pet allergies",
            "finding a good veterinarian",
            "traveling with a pet",
            "grooming at home",
            "caring for a senior pet",
            "introducing pets to each other",
            "crate training a dog",
            "setting up a litter box",
            "finding a dog walker",
            "keeping indoor pets entertained",
            "preparing a pet for a move",
        ],
    },
    "automotive": {
        "description": "Car maintenance, repairs, purchases",
        "subcategories": [
            "changing oil on schedule",
            "choosing the right tires",
            "diagnosing a check engine light",
            "replacing a car battery",
            "buying a used car",
            "comparing car insurance",
            "handling a roadside emergency",
            "improving fuel efficiency",
            "detailing a car at home",
            "preparing a car for winter",
            "planning a long drive",
            "cleaning the inside of a car",
            "finding a trustworthy mechanic",
            "dealing with a flat tire",
            "choosing between leasing and buying",
        ],
    },
    "event_planning": {
        "description": "Parties, gatherings, celebrations",
        "subcategories": [
            "planning a birthday party",
            "organizing a small wedding",
            "hosting a baby shower",
            "setting up a graduation celebration",
            "arranging a dinner party",
            "coordinating a potluck",
            "planning an anniversary event",
            "organizing kids entertainment",
            "choosing party decorations",
            "managing a guest list",
            "planning a housewarming",
            "organizing a backyard barbecue",
            "hosting a game night with friends",
            "putting together a picnic",
            "planning a farewell party for a coworker",
        ],
    },
    "relationships_social": {
        "description": "Dating, friendships, and interpersonal dynamics outside family",
        "subcategories": [
            "planning a first date",
            "reconnecting with an old friend",
            "handling a disagreement with a partner",
            "meeting a partner's family",
            "making new friends as an adult",
            "keeping in touch with distant friends",
            "deciding whether to move in with a partner",
            "navigating a long-distance relationship",
            "apologizing after an argument",
            "going to a friend's wedding alone",
            "hosting a friend visiting from out of town",
            "setting boundaries with a friend",
            "handling a friendship that has drifted apart",
            "introducing a partner to friends",
            "finding a thoughtful gift for a close friend",
        ],
    },
    "self_care_mental_health": {
        "description": "Everyday wellbeing, routines, and emotional self-care",
        "subcategories": [
            "building a morning routine",
            "finding time to relax",
            "dealing with burnout at work",
            "managing anxiety before a big event",
            "disconnecting from social media",
            "setting small goals for the week",
            "creating an evening wind-down routine",
            "handling a stressful season at work",
            "finding a hobby that helps you recharge",
            "taking a proper lunch break",
            "saying no to extra commitments",
            "setting up a quiet space at home",
            "dealing with a rough week",
            "making time for friends while busy",
            "getting back into a routine after a trip",
        ],
    },
    "moving_housing": {
        "description": "Finding a place, moving logistics, setting up a new home",
        "subcategories": [
            "finding an apartment to rent",
            "packing for a move",
            "hiring movers",
            "setting up utilities in a new place",
            "breaking a lease early",
            "comparing neighborhoods before moving",
            "getting rid of stuff before a move",
            "unpacking after a move",
            "finding a roommate",
            "decorating a new apartment on a budget",
            "handling the transition to a new city",
            "setting up internet in a new place",
            "doing a walkthrough before moving in",
            "coordinating move-in day",
            "dealing with a move that runs long",
        ],
    },
    "fashion_personal_style": {
        "description": "Everyday clothing, grooming, and personal style",
        "subcategories": [
            "building a basic wardrobe",
            "dressing for a job interview",
            "finding clothes that fit well",
            "choosing a haircut",
            "dressing for different weather",
            "putting together an outfit for a wedding",
            "finding a pair of comfortable everyday shoes",
            "refreshing a wardrobe without spending a lot",
            "dressing for a business casual workplace",
            "picking a watch or simple accessory",
            "shopping for clothes that last",
            "caring for clothes so they last longer",
            "trying a new style",
            "getting clothes tailored",
            "packing an outfit for an out-of-town event",
        ],
    },
    "gardening_outdoors": {
        "description": "Plants, yards, and outdoor spaces at home",
        "subcategories": [
            "starting a vegetable garden",
            "keeping houseplants alive",
            "setting up a bird feeder",
            "caring for a lawn",
            "growing herbs on a balcony",
            "building a small raised bed",
            "choosing plants for a shady spot",
            "dealing with weeds in the yard",
            "setting up outdoor seating",
            "planting flowers in spring",
            "winterizing a garden",
            "keeping squirrels out of a bird feeder",
            "starting seeds indoors",
            "pruning a small tree",
            "setting up a compost bin",
        ],
    },
}
SETTINGS = [
    # Food & drink venues
    "a coffee shop",
    "a café",
    "a bakery",
    "a restaurant",
    "a bookstore café",
    "a sandwich shop",
    "a deli",
    "a diner",
    "a pub",
    "a cafeteria",
    # Specific spots within food & drink venues
    "a booth at a restaurant",
    "a window seat at a coffee shop",
    "a patio outside a café",
    "a corner table at a café",
    "a table outside a bakery",
    "a bar stool at a café counter",
    "a nook in a café",
    "a quiet corner of a café",
    "a bench outside a coffee shop",
    "a communal table at a café",
    # Domestic
    "a kitchen",
    "a living room",
    "a dining room",
    "a porch",
    "a balcony",
    "a backyard",
    "a den",
    "a study room",
    # Workplace
    "a break room at work",
    "a conference room",
    # Public / transit / shared
    "a library",
    "a hotel lobby",
    "a waiting area",
    "a food court seating area",
    "a lounge area",
    "a seating area in a lobby",
    "a common area of an apartment building",
    # Outdoors
    "a park bench",
    "a bench in a garden",
    "a courtyard bench",
]

UNIVERSITIES_ELITE = [
    # Ivies
    "Harvard", "Yale", "Princeton", "Columbia", "Penn", "Brown", "Cornell", "Dartmouth",

    # Elite research universities
    "Stanford", "MIT", "Caltech", "Carnegie Mellon", "University of Chicago", "Duke",
    "Johns Hopkins",

    # Elite international
    "Oxford", "Cambridge", "ETH Zurich",

    # Elite public
    "Berkeley",
]

UNIVERSITIES_NONELITE = [
    "Cal State Fullerton",
    "Cal State Northridge",
    "San Diego State",
    "University of North Texas",
    "University of Central Florida",
    "University of Northern Iowa",
    "Florida Atlantic",
    "West Chester University",
    "Bowling Green State",
    "Sam Houston State",
    "Wichita State",
    "East Tennessee State",
    "Kennesaw State",
    "Georgia Southern",
    "Western Kentucky University",
    "Northern Arizona University",
    "University of Toledo",
    "Eastern Michigan University",
    "Middle Tennessee State",
]
