#%%
"""Character pools and the 70 task categories for each domain."""

NAMES = [
    "Jordan", "Sam", "Morgan", "Casey", "Riley", "Quinn", "Avery", "Taylor", "Jamie", "Drew",
    "Skyler", "Reese", "Finley", "Rowan", "Sage", "Parker", "Cameron", "Charlie", "Dakota",
    "Devon", "Emerson", "Harper", "Hayden", "Jesse", "Kai", "Kendall", "Lane", "Lee", "Marley",
    "Micah", "Noel", "Phoenix", "River", "Robin", "Shawn", "Sidney", "Terry", "Tristan", "Wren",
    "Mike", "Danny", "Chris", "Matt", "Jake", "Ryan", "Brian", "Kevin", "Tom", "Ben", "Nick",
    "Steve", "Eric", "Jason", "Mark", "David", "Adam", "Andrew", "Brad", "Brandon", "Caleb",
    "Cody", "Daniel", "Ethan", "Frank", "George", "Greg", "Henry", "Jack", "James", "Jeff", "John",
    "Josh", "Justin", "Kyle", "Luke", "Nathan", "Noah", "Paul", "Peter", "Robert", "Scott", "Sean",
    "Tim", "Tyler", "Will", "Zach", "Sarah", "Emily", "Jessica", "Rachel", "Lauren", "Amanda",
    "Megan", "Katie", "Lisa", "Jenny", "Nicole", "Ashley", "Heather", "Stephanie", "Becky", "Tina",
    "Abigail", "Allison", "Anna", "Brittany", "Chloe", "Courtney", "Danielle", "Elizabeth", "Emma",
    "Erin", "Gabrielle", "Grace", "Hannah", "Jillian", "Kelly", "Kim", "Kristen", "Laura",
    "Madison", "Molly", "Natalie", "Olivia", "Samantha", "Vanessa", "Victoria", "Zoe", "Priya",
    "Raj", "Ananya", "Vikram", "Neha", "Arjun", "Kavita", "Sanjay", "Deepa", "Amit", "Sunita",
    "Rohan", "Meera", "Aditya", "Pooja", "Nikhil", "Asha", "Rahul", "Kiran", "Divya", "Isha",
    "Shreya", "Varun", "Siddharth", "Gaurav", "Pranav", "Shruti", "Sneha", "Manish", "Suresh",
    "Jaya", "Mahesh", "Payal", "Tanvi", "Anil", "Ritu", "Wei", "Ming", "Jing", "Chen", "Lin",
    "Hui", "Xin", "Lei", "Yan", "Feng", "Hong", "Ping", "Ling", "Jun", "Mei", "Tao", "Li", "Xiao",
    "Ying", "Lan", "Bo", "Rui", "Yao", "Qiang", "Shu", "Zhi", "Zhen", "Ting", "Guo", "Shan",
    "Yuki", "Kenji", "Sakura", "Haruto", "Aiko", "Takeshi", "Naomi", "Ryo", "Akira", "Hiroshi",
    "Hana", "Kaito", "Emi", "Satoshi", "Yoko", "Ren", "Mika", "Shin", "Aya", "Daichi", "Mai",
    "Ryota", "Carlos", "Maria", "Diego", "Sofia", "Miguel", "Isabella", "Javier", "Lucia", "Rosa",
    "Marco", "Elena", "Luis", "Carmen", "Pedro", "Ana", "Rafael", "Juan", "Jose", "Andres",
    "Fernando", "Gabriel", "Alejandro", "Francisco", "Ricardo", "Manuel", "Pablo", "Roberto",
    "Daniela", "Gabriela", "Valeria", "Camila", "Mariana", "Natalia", "Patricia", "Veronica",
    "Luisa", "Luca", "Giulia", "Francesca", "Alessandro", "Chiara", "Matteo", "Valentina",
    "Giovanni", "Paolo", "Stefano", "Federico", "Giorgio", "Filippo", "Alberto", "Claudia",
    "Silvia", "Martina", "Elisa", "Giovanna", "Davide", "Simone", "Fatima", "Omar", "Layla",
    "Hassan", "Zahra", "Karim", "Nadia", "Amir", "Ali", "Reza", "Yasmin", "Samira", "Farah",
    "Noor", "Amina", "Khalid", "Hadi", "Samir", "Salma", "Maryam", "Zain", "Rami", "Jin", "Soo",
    "Minji", "Hyun", "Jae", "Yuna", "Jisoo", "Jihoon", "Seojun", "Eunji", "Sumin", "Taehyun",
    "Hyejin", "Seungmin", "Joon", "Jiwoo", "Oleksandr", "Katya", "Dmitri", "Anya", "Ivan",
    "Natasha", "Andrei", "Nikolai", "Sergei", "Mikhail", "Viktor", "Olga", "Irina", "Anastasia",
    "Yulia", "Svetlana", "Pavel", "Boris", "Mila", "Kwame", "Amara", "Kofi", "Zara", "Nia",
    "Malik", "Imani", "Jabari", "Adewale", "Chidi", "Chioma", "Ngozi", "Nnamdi", "Lerato",
    "Thandi", "Zanele", "Remy", "Camille", "Julien", "Pierre", "Luc", "Hugo", "Celine", "Amelie",
    "Sophie", "Andre", "Marcel", "Nina", "Lars", "Sven", "Ingrid", "Greta", "Anja", "Heidi",
    "Klaus", "Hans", "Lea", "Nils", "Anh", "Thuy", "Trang", "Huy", "Tuan", "Phuong", "Lan", "Minh",
    "Bao", "Aria", "Narin", "Somchai", "Priyom", "Lani", "Mariel",
]
WORDS_COMMON = [
    "tomorrow", "yesterday", "weekend", "morning", "afternoon", "evening", "midnight", "deadline",
    "schedule", "calendar", "hourly", "weekly", "monthly", "later", "earlier", "coffee", "laptop",
    "phone", "notebook", "window", "desk", "chair", "keyboard", "screen", "folder", "charger",
    "headphones", "printer", "bottle", "blanket", "remember", "forget", "check", "update",
    "review", "confirm", "finish", "start", "pause", "continue", "adjust", "organize", "compare",
    "arrange", "submit", "quick", "simple", "perfect", "great", "excellent", "solid", "smooth",
    "clean", "fresh", "ready", "basic", "obvious", "tricky", "urgent", "flexible", "office",
    "home", "building", "floor", "room", "hallway", "parking", "elevator", "lobby", "kitchen",
    "garage", "bedroom", "bathroom", "garden", "basement", "manager", "colleague", "teammate",
    "intern", "boss", "client", "vendor", "partner", "assistant", "director", "neighbor", "cousin",
    "landlord", "stranger", "guest", "busy", "tired", "relieved", "frustrated", "excited",
    "confused", "confident", "nervous", "curious", "satisfied", "overwhelmed", "relaxed",
    "impatient", "grateful", "skeptical", "email", "message", "meeting", "lunch", "break",
    "project", "report", "document", "version", "draft", "budget", "recipe", "password",
    "reminder", "backup",
]
TOPIC_POOLS = {
    "tables": {
        "description": "Working with data tables and spreadsheets — entering data, "
        "organizing records, building formulas and pivots, formatting, "
        "charting, and cleaning up tabular data",
        "subcategories": [
            "entering rows of inventory data into a structured spreadsheet",
            "cleaning up a messy customer contact list and standardizing the columns",
            "building a pivot table that summarizes quarterly sales by region",
            "setting up conditional formatting to flag overdue invoices in a tracker",
            "merging two spreadsheets and removing duplicate entries",
            "creating a Gantt-chart spreadsheet for tracking project milestones",
            "organizing a personal book collection into a sortable spreadsheet",
            "building a household budget template with category subtotals and running balances",
            "converting a long unformatted CSV export into a clean labeled table",
            "setting up a reusable form for logging daily inventory counts",
            "tabulating survey responses with frequency counts per question",
            "standardizing date formats across columns in a customer spreadsheet",
            "transcribing handwritten meeting notes into a formatted table",
            "cataloguing a collection of items with descriptions and categories",
            "reformatting a bibliography into a consistent citation style",
            "sorting and labeling files into a consistent folder system",
            "building a tracking sheet for monthly household expenses",
            "creating a schedule grid for shift rotations",
            "converting a free-text address list into normalized columns",
            "setting up a VLOOKUP across two product sheets to join SKU data",
            "writing nested IF formulas to categorize transactions in a ledger",
            "setting up data validation dropdowns for a project tracker",
            "building a dashboard sheet with summary KPIs at the top",
            "constructing a sparkline column to visualize per-row trends",
            "setting up index-match formulas to pull data across multiple sheets",
            "configuring an automatic running total in a daily-log spreadsheet",
            "writing a SUMIFS formula to total expenses by department and month",
            "building a tracker for warranty expiry dates with sortable filters",
            "reorganizing a wide-format dataset into long format for analysis",
            "writing a formula to compute weighted averages across columns",
            "setting up frozen panes and header rows in a long data sheet",
            "building a depreciation schedule for office equipment in a spreadsheet",
            "assembling a stacked bar chart from a sales-by-region table",
            "creating a multi-tab workbook with linked summary cells across tabs",
            "writing a TEXTJOIN formula to concatenate address fields cleanly",
            "tracing and resolving circular references in a complex spreadsheet",
            "configuring a named range and using it across multiple formulas",
            "building a price comparison table for a list of suppliers",
            "reformatting a roster spreadsheet with consistent name capitalization",
            "creating a sortable inventory sheet with low-stock highlighting",
            "writing a COUNTIFS formula to break down survey results by demographic",
            "building an attendance grid with a per-month percentage summary",
            "setting up a mortgage amortization table from scratch",
            "converting raw timestamps into separate date and time-of-day columns",
            "building a workout-tracking spreadsheet with weekly progress columns",
            "cleaning up a list of email addresses and removing invalid entries",
            "creating a project-task table with status, owner, and due-date columns",
            "building a sortable expense report from a stack of paper receipts",
            "assembling a multi-year sales comparison table with year-over-year deltas",
            "setting up a checkbook register spreadsheet with running balance",
            "creating a recipe-and-ingredient inventory table for a small bakery",
            "writing a CONCATENATE formula to build labels from multiple columns",
            "building a contact tracker with consistent phone-number formatting",
            "setting up a payroll spreadsheet with overtime calculations",
            "organizing class grades into a summary table with weighted-average column",
            "creating a vehicle-fleet maintenance log spreadsheet",
            "building a frequency table of issue categories from a customer-support log",
            "configuring sparkline visualizations across a row of monthly metrics",
            "converting a free-text invoice list into a normalized line-item table",
            "setting up a multi-criteria sort on a contact list (region, then last name)",
            "building an asset-tracking spreadsheet with serial numbers and locations",
            "computing column-level summary statistics for a research dataset",
            "cleaning duplicate rows from a multi-thousand-row customer table",
            "setting up a school-supplies inventory sheet with reorder triggers",
            "writing an IFERROR wrapper around a complex VLOOKUP chain",
            "building a quote-comparison spreadsheet from competing vendor bids",
            "setting up a sortable book-borrowing log for a school library",
            "building a multi-month cash-flow projection spreadsheet",
            "organizing a list of donor records into a sortable database",
            "creating a recurring-task tracker with completion timestamps",
        ],
    },
    "emotional_support": {
        "description": "Providing emotional support — listening, consoling, "
        "validating, and helping someone process difficult "
        "feelings around loss, stress, relationships, work, "
        "family, and health",
        "subcategories": [
            "unexpectedly losing their job",
            "a painful breakup of their own",
            "the death of their long-time pet",
            "the stress of caring for their aging parent",
            "failing an important exam",
            "receiving a difficult medical diagnosis",
            "the anxiety of moving to a new city alone",
            "feeling like they don't belong at their workplace",
            "their adult child stopping speaking to them",
            "being overwhelmed after becoming a new parent",
            "their long-term relationship ending unexpectedly",
            "their parent being diagnosed with a terminal illness",
            "persistent feelings of loneliness",
            "guilt about a decision made years ago",
            "the shock of a sudden death in the family",
            "feeling invisible and undervalued in their friendships",
            "a difficult miscarriage",
            "the emotional weight of caregiver burnout",
            "financial stress with no visible way out",
            "feeling like they're failing as a parent",
            "their adult sibling struggling with addiction",
            "feeling deeply ashamed after a public mistake at work",
            "not being able to conceive after years of trying",
            "reeling from an unexpected layoff in their first month",
            "being passed over for a long-awaited promotion",
            "grief on the first anniversary of a loss",
            "their adult child being in legal trouble",
            "being mistreated by an in-law",
            "anxiety before a major medical procedure",
            "their responsibilities as the eldest sibling",
            "not getting into the graduate program they wanted",
            "their long-time best friend abruptly cutting them off",
            "a difficult childhood memory resurfacing",
            "feeling deeply alone at school",
            "guilt about putting a parent in long-term care",
            "recovering from a serious illness",
            "the disappointment of an engagement ending",
            "whether to leave a long marriage",
            "their small business unexpectedly closing",
            "their teenager struggling with mental health",
            "being estranged from their parents for years",
            "the demands of a new caregiving role",
            "their adult child moving to another continent",
            "feeling stuck in a job they can't afford to leave",
            "anxiety the night before a difficult conversation",
            "body-image distress after a serious illness",
            "their spouse being deployed for an extended tour",
            "rebuilding life after a divorce",
            "the loss of a friendship they expected to last forever",
            "feeling like they're constantly failing as a single parent",
            "losing a parent before they could reconcile",
            "their dream of having children not coming true",
            "the disorientation of becoming an empty nester",
            "grieving a beloved aunt or grandparent",
            "chronic pain that doctors can't explain",
            "the slow decline of a parent with dementia",
            "the grief of a stillbirth",
            "feeling like a burden to everyone in their life",
            "their long-time pet having to be put to sleep",
            "feeling alienated from a faith community they once loved",
            "the emotional fallout of a deeply unfair court ruling",
            "being the only sober person in their immediate family",
            "guilt about a failed marriage",
            "their adult child no longer speaking to them",
            "the loneliness of a first holiday without a loved one",
            "their roommate suddenly moving out without explanation",
            "their home being lost in a fire",
            "reeling from a close friend's death",
            "the embarrassment of a public falling-out",
            "the responsibilities of dual caregiving",
        ],
    },
}

# Latin/Botany appendix replication.
TOPIC_POOLS.update(
    {
        "latin": {
            "description": "Working with Latin language — translation, grammar, literature, "
            "and composition",
            "subcategories": [
                "translating a short passage from Cicero's letters",
                "parsing the grammar of a sentence from Virgil's Aeneid",
                "working through Latin noun declension drills",
                "conjugating irregular Latin verbs in the subjunctive",
                "translating an English paragraph into Latin prose",
                "scanning the hexameter in a passage from Ovid's Metamorphoses",
                "analyzing the rhetoric in one of Cicero's orations",
                "reading a passage from Caesar's Gallic Wars",
                "translating a section from Seneca's moral letters",
                "working through ablative absolute constructions",
                "comparing different translations of a Horace ode",
                "parsing indirect speech constructions in Livy",
                "studying the use of the gerundive in formal prose",
                "translating a passage from Catullus's poetry",
                "working through conditional sentences in Latin",
                "analyzing meter and style in Lucretius's De Rerum Natura",
                "reading a section from Pliny the Younger's letters",
                "practicing Latin composition using a set topic",
                "studying deponent verbs and their usage patterns",
                "translating an inscription from a Roman monument",
                "working through purpose clauses and result clauses",
                "reading a passage from Tacitus's Annals",
                "analyzing the use of participles in a passage from Sallust",
                "translating a section from Augustine's Confessions",
                "studying the accusative with infinitive construction",
                "working through relative clauses in complex sentences",
                "reading and translating a passage from Petronius's Satyricon",
                "comparing verb tenses in a narrative passage from Livy",
                "practicing sight-reading with an unseen Latin passage",
                "analyzing figures of speech in Virgil's Eclogues",
                "translating a passage from Martial's epigrams",
                "working through the sequence of tenses in subjunctive clauses",
                "studying the uses of the dative case in Latin prose",
                "reading a passage from Suetonius's Lives of the Caesars",
                "translating a medieval Latin hymn into English",
                "analyzing word order and emphasis in a passage from Cicero",
                "working through fear clauses and indirect commands",
                "reading and parsing a passage from Juvenal's satires",
                "studying the historical development of Latin verb forms",
                "composing a short Latin epitaph in classical style",
                "translating a passage from Apuleius's The Golden Ass",
                "working through the uses of the genitive case in Latin",
                "reading a passage from Ammianus Marcellinus's historical accounts",
                "analyzing the prose rhythm in a Ciceronian period",
                "translating a passage from Vitruvius's De Architectura",
                "studying the formation and use of Latin supines",
                "comparing the styles of Caesar and Sallust in historical narrative",
                "working through temporal clauses with cum and postquam",
                "translating a passage from Boethius's Consolation of Philosophy",
                "analyzing the use of chiasmus and anaphora in Latin oratory",
                "reading a passage from Columella's treatise on agriculture",
                "working through comparative and superlative adjective forms",
                "translating a passage from the Vulgate Bible into English",
                "studying the use of the historic present in narrative Latin",
                "analyzing the structure of a Ciceronian letter opening and closing",
                "working through concessive clauses using quamquam and licet",
                "reading a passage from Quintilian's Institutio Oratoria",
                "translating a legal formula from a Roman law text",
                "studying enclitics and their effect on word stress in Latin verse",
                "comparing the elegiac couplets of Tibullus and Propertius",
                "working through reported speech using subjunctive mood changes",
                "reading a passage from Gellius's Attic Nights",
                "translating a passage from Celsus's medical writings",
                "analyzing the narrative techniques in a passage from Apuleius",
                "studying the vocative case and forms of direct address",
                "working through proviso clauses using dum and modo",
                "reading and scanning a passage from Statius's Thebaid",
                "translating a passage from Frontinus's treatise on aqueducts",
                "practicing Latin-to-English translation of a philosophical "
                "argument from Cicero's De Officiis",
                "studying the differences between classical and medieval Latin vocabulary",
            ],
        },
        "botany": {
            "description": "Working with botany — plant identification, anatomy, physiology, "
            "taxonomy, and ecology",
            "subcategories": [
                "identifying a flowering plant using a dichotomous key",
                "examining the cross-section anatomy of a monocot stem",
                "classifying a specimen into the correct plant family",
                "comparing leaf venation patterns in dicots and monocots",
                "labeling the parts of a dissected flower under a hand lens",
                "studying the stages of pollen germination on a stigma",
                "pressing and mounting a herbarium specimen for the collection",
                "analyzing the growth rings in a wood cross-section",
                "identifying common lichens on a field walk in the woods",
                "drawing and labeling a longitudinal section of a root tip",
                "studying the structure of guard cells and stomatal opening",
                "keying out a fern species using sporangium characteristics",
                "examining phloem and xylem tissue under a light microscope",
                "comparing the seed structure of a gymnosperm and an angiosperm",
                "mapping the distribution of plant species along a transect line",
                "studying the nitrogen cycle and its role in plant nutrition",
                "observing phototropism and gravitropism in seedling experiments",
                "identifying tree species by bark texture and twig morphology",
                "analyzing the effect of light intensity on the rate of photosynthesis",
                "sketching the life cycle of a moss from spore to sporophyte",
                "examining mycorrhizal associations in root samples",
                "comparing the anatomy of C3 and C4 leaf cross-sections",
                "identifying aquatic plant adaptations in a pond sample",
                "studying the process of secondary growth in a woody stem",
                "collecting and identifying wildflowers for a species inventory",
                "examining the ultrastructure of chloroplasts in electron micrographs",
                "studying seed dispersal mechanisms across different plant families",
                "analyzing soil pH and its effect on local plant community composition",
                "comparing the reproductive structures of mosses and liverworts",
                "identifying common agricultural weeds from a field sample",
                "studying allelopathy by testing plant extracts on seed germination",
                "examining the role of auxin in apical dominance",
                "classifying succulent plants by their water-storage adaptations",
                "identifying edible wild plants and their distinguishing features",
                "studying the Crassulacean acid metabolism pathway in desert plants",
                "analyzing pollen morphology under a compound microscope",
                "comparing the leaf anatomy of sun leaves and shade leaves",
                "examining the structure and function of root hairs in nutrient uptake",
                "studying the ecological succession of plant communities after a disturbance",
                "identifying invasive plant species and discussing management strategies",
                "examining the anatomy of a legume root nodule and nitrogen fixation",
                "comparing the floral structures of wind-pollinated and "
                "insect-pollinated plants",
                "studying the Calvin cycle and carbon fixation in chloroplasts",
                "identifying grass species by ligule, auricle, and inflorescence type",
                "examining the development of a fruit from flower to mature ovary",
                "studying the water potential gradient from soil to leaf",
                "comparing the bark and wood anatomy of hardwoods and softwoods",
                "identifying carnivorous plants and their trapping mechanisms",
                "examining the effect of ethylene on fruit ripening",
                "studying the structure of a compound leaf versus a simple leaf",
                "analyzing the distribution of trichomes on leaf surfaces",
                "comparing the germination requirements of different seed types",
                "examining the role of gibberellins in stem elongation",
                "identifying parasitic plants and their haustorial connections",
                "studying the anatomy of a grass stem and its intercalary meristems",
                "comparing the spore-producing structures of horsetails and club mosses",
                "examining the effect of day length on flowering in photoperiodic plants",
                "identifying conifer species by needle arrangement and cone morphology",
                "studying the role of abscisic acid in stomatal closure during drought",
                "analyzing the zonation of seaweed species along a rocky shore",
                "examining the structure of a pine ovulate cone at different "
                "developmental stages",
                "comparing epiphytic and terrestrial orchid root anatomy",
                "studying the formation of annual rings and their use in dendrochronology",
                "identifying medicinal plants and their traditional uses from a "
                "field collection",
                "examining the process of double fertilization in angiosperms",
                "studying the structure and function of lenticels in woody stems",
                "comparing the leaf modifications in xerophytes and hydrophytes",
                "examining the role of cytokinins in cell division and shoot growth",
                "identifying bryophyte species from a forest floor sample",
                "studying the phytochrome system and its role in seed "
                "germination and shade avoidance",
            ],
        },
    }
)
