#%%
NAMES_HELPSEEKER = [
    "Jordan", "Sam", "Morgan", "Casey", "Riley", "Quinn", "Avery", "Taylor", "Jamie", "Drew",
    "Skyler", "Reese", "Finley", "Rowan", "Sage", "Parker", "Cameron", "Charlie", "Dakota",
    "Devon", "Emerson", "Harper", "Hayden", "Jesse", "Kai", "Kendall", "Lane", "Lee", "Marley",
    "Micah", "Noel", "Phoenix", "River", "Robin", "Shawn", "Sidney", "Terry", "Tristan", "Wren",
    "Mike", "Danny", "Chris", "Matt", "Jake", "Ryan", "Brian", "Kevin", "Tom", "Ben", "Nick",
    "Steve", "Eric", "Jason", "Mark", "David", "Adam", "Andrew", "Brad", "Brandon", "Caleb",
    "Cody", "Daniel", "Ethan", "Frank", "George", "Greg", "Henry", "Jack", "James", "Jeff", "John",
    "Josh", "Justin", "Kyle", "Luke", "Nathan", "Noah", "Paul", "Peter", "Robert", "Scott", "Sean",
    "Tim", "Tyler", "Will", "Zach", "Sarah", "Emily", "Jessica", "Rachel", "Lauren", "Amanda",
    "Megan", "Katie", "Lisa", "Jenny", "Nicole", "Ashley", "Heather", "Stephanie", "Becky", "Tina",
    "Abigail", "Allison", "Anna", "Brittany", "Chloe", "Courtney", "Danielle", "Elizabeth", "Emma",
    "Erin", "Gabrielle", "Grace", "Hannah", "Jillian", "Julia", "Kelly", "Kim", "Kristen", "Laura",
    "Madison", "Molly", "Natalie", "Olivia", "Samantha", "Vanessa", "Victoria", "Zoe", "Priya",
    "Raj", "Ananya", "Vikram", "Neha", "Arjun", "Kavita", "Sanjay", "Deepa", "Amit", "Sunita",
    "Rohan", "Meera", "Aditya", "Pooja", "Nikhil", "Asha", "Rahul", "Kiran", "Divya", "Isha",
    "Shreya", "Varun", "Siddharth", "Gaurav", "Pranav", "Shruti", "Sneha", "Manish", "Suresh",
    "Jaya", "Mahesh", "Payal", "Tanvi", "Anil", "Ritu", "Wei", "Ming", "Jing", "Chen", "Lin",
    "Hui", "Xin", "Lei", "Yan", "Feng", "Hong", "Ping", "Ling", "Jun", "Mei", "Tao", "Li", "Xiao",
    "Ying", "Lan", "Bo", "Rui", "Yao", "Qiang", "Shu", "Zhi", "Zhen", "Ting", "Guo", "Shan",
    "Yuki", "Kenji", "Sakura", "Haruto", "Aiko", "Takeshi", "Naomi", "Ryo", "Akira", "Hiroshi",
    "Hana", "Kaito", "Emi", "Satoshi", "Yoko", "Ren", "Mika", "Shin", "Aya", "Daichi", "Mai",
    "Ryota", "Carlos", "Maria", "Diego", "Sofia", "Miguel", "Isabella", "Javier", "Lucia", "Rosa",
    "Marco", "Elena", "Luis", "Carmen", "Pedro", "Ana", "Rafael", "Juan", "Jose", "Andres",
    "Fernando", "Gabriel", "Alejandro", "Francisco", "Ricardo", "Manuel", "Pablo", "Roberto",
    "Daniela", "Gabriela", "Valeria", "Camila", "Mariana", "Natalia", "Patricia", "Veronica",
    "Luisa", "Luca", "Giulia", "Francesca", "Alessandro", "Chiara", "Matteo", "Valentina",
    "Giovanni", "Paolo", "Stefano", "Federico", "Giorgio", "Filippo", "Alberto", "Claudia",
    "Silvia", "Martina", "Elisa", "Giovanna", "Davide", "Simone", "Fatima", "Omar", "Layla",
    "Hassan", "Zahra", "Karim", "Nadia", "Amir", "Ali", "Reza", "Yasmin", "Samira", "Farah",
    "Noor", "Amina", "Khalid", "Hadi", "Samir", "Salma", "Maryam", "Zain", "Rami", "Jin", "Soo",
    "Minji", "Hyun", "Jae", "Yuna", "Jisoo", "Jihoon", "Seojun", "Eunji", "Sumin", "Taehyun",
    "Hyejin", "Seungmin", "Joon", "Jiwoo", "Oleksandr", "Katya", "Dmitri", "Anya", "Ivan",
    "Natasha", "Andrei", "Nikolai", "Sergei", "Mikhail", "Viktor", "Olga", "Irina", "Anastasia",
    "Yulia", "Svetlana", "Pavel", "Boris", "Mila", "Kwame", "Amara", "Kofi", "Zara", "Malik",
    "Jabari", "Adewale", "Chidi", "Chioma", "Ngozi", "Nnamdi", "Lerato", "Thandi", "Zanele",
    "Remy", "Camille", "Julien", "Pierre", "Luc", "Hugo", "Celine", "Amelie", "Sophie", "Andre",
    "Marcel", "Nina", "Lars", "Sven", "Ingrid", "Greta", "Anja", "Heidi", "Klaus", "Hans", "Lea",
    "Nils", "Anh", "Thuy", "Trang", "Huy", "Tuan", "Phuong", "Lan", "Minh", "Bao", "Aria", "Narin",
    "Somchai", "Priyom", "Lani", "Mariel",
]
WORDS_COMMON = [
    "tomorrow", "yesterday", "weekend", "morning", "afternoon", "evening", "midnight", "deadline",
    "schedule", "calendar", "hourly", "weekly", "monthly", "later", "earlier", "coffee", "laptop",
    "phone", "notebook", "window", "desk", "chair", "keyboard", "screen", "folder", "charger",
    "headphones", "printer", "bottle", "blanket", "remember", "forget", "check", "update",
    "review", "confirm", "finish", "start", "pause", "continue", "adjust", "organize", "compare",
    "arrange", "submit", "quick", "simple", "perfect", "great", "excellent", "solid", "smooth",
    "clean", "fresh", "ready", "basic", "obvious", "tricky", "urgent", "flexible", "office",
    "home", "building", "floor", "room", "hallway", "parking", "elevator", "lobby", "kitchen",
    "garage", "bedroom", "bathroom", "garden", "basement", "manager", "colleague", "teammate",
    "intern", "boss", "client", "vendor", "partner", "assistant", "director", "neighbor", "cousin",
    "landlord", "stranger", "guest", "busy", "tired", "relieved", "frustrated", "excited",
    "confused", "confident", "nervous", "curious", "satisfied", "overwhelmed", "relaxed",
    "impatient", "grateful", "skeptical", "email", "message", "meeting", "lunch", "break",
    "project", "report", "document", "version", "draft", "budget", "recipe", "password",
    "reminder", "backup",
]
SETTINGS = [
    # Food & drink venues
    "a coffee shop",
    "a café",
    "a bakery",
    "a restaurant",
    "a bookstore café",
    "a sandwich shop",
    "a deli",
    "a diner",
    "a pub",
    "a cafeteria",
    # Specific spots within food & drink venues
    "a booth at a restaurant",
    "a window seat at a coffee shop",
    "a patio outside a café",
    "a corner table at a café",
    "a table outside a bakery",
    "a bar stool at a café counter",
    "a nook in a café",
    "a quiet corner of a café",
    "a bench outside a coffee shop",
    "a communal table at a café",
    # Domestic
    "a kitchen",
    "a living room",
    "a dining room",
    "a porch",
    "a balcony",
    "a backyard",
    "a den",
    "a study room",
    # Workplace
    "a break room at work",
    "a conference room",
    # Public / transit / shared
    "a library",
    "a hotel lobby",
    "a waiting area",
    "a food court seating area",
    "a lounge area",
    "a seating area in a lobby",
    "a common area of an apartment building",
    # Outdoors
    "a park bench",
    "a bench in a garden",
    "a courtyard bench",
]

UNIVERSITIES_ELITE = [
    # Ivies
    "Harvard", "Yale", "Princeton", "Columbia", "Penn", "Brown", "Cornell", "Dartmouth",

    # Elite research universities
    "Stanford", "MIT", "Caltech", "Carnegie Mellon", "University of Chicago", "Duke",
    "Johns Hopkins",

    # Elite international
    "Oxford", "Cambridge", "ETH Zurich",

    # Elite public
    "Berkeley",
]

UNIVERSITIES_NONELITE = [
    "Cal State Fullerton",
    "Cal State Northridge",
    "San Diego State",
    "University of North Texas",
    "University of Central Florida",
    "University of Northern Iowa",
    "Florida Atlantic",
    "West Chester University",
    "Bowling Green State",
    "Sam Houston State",
    "Wichita State",
    "East Tennessee State",
    "Kennesaw State",
    "Georgia Southern",
    "Western Kentucky University",
    "Northern Arizona University",
    "University of Toledo",
    "Eastern Michigan University",
    "Middle Tennessee State",
]
